### ISSUE TITLE
Section 5.4.2 and 5.4.3 Race types

### ISSUE THREAD

**Issue by jmarente** [crononauta/tally-ho#6]
Section 5.4.2 Mark race as inactive:
Right now, the races are not stored in database and are use as Enum constants. In order to implement this functionality would be necessary to store these elements in database and this would imply changes in the current model application, and all places in code where these enums are used should be modified as well. Should we apply all these changes?

Section 5.4.3 Marking Race as Available for Release:
To implement this requirement, the same changes explained in above should be implemented.

**Comment by mrajayp** [comment]
Yeah, I feared as much. We will need to make these changes. The goal is to ultimately remove the use of enums for electoral parameters in order to create a more manageable system. 

I would note however, if we are concerned that changing the data models will impose risk we should proceed carefully and potentially just update the constants for now. With little time for testing, and a strong desire to have a predictable system I don't feel this is worth the risk prior to this election.

**Comment by jmarente** [comment]
I think we may have misunderstood about what we really need to do in this requirement. When you mean "mark a race as inactive", is it mean the races type  (General, Woman, Component Amazihg, ...) which are used as enums? or do you mean the races that are associated to a race type that can be found in the Races Progress Report [1] ? they are stored in database. This would really change the approach to implement this.

[1] http://scytl-libia test.dev.crononauta.net/reports/internal/race

**Comment by mrajayp** [comment]
Sorry, I am having trouble accessing the link, as i still don't seem able to get into the system.

But if memory serves me correctly, yes, the above is true. It is not the race type, but the races associated with the race type. That said, I am not sure we need to prioritise this.
